name = "Einops"
uuid = "e3ce28c8-8bfb-4704-8add-e3e7f14b55c9"
authors = ["Anton Oresten <antonoresten@gmail.com> and contributors"]
version = "0.1.1"

[deps]
ChainRulesCore = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"

[compat]
ChainRulesCore = "1.7"
EllipsisNotation = "1"
LinearAlgebra = "1"
OMEinsum = "0.8"
Statistics = "1"
Zygote = "0.6, 0.7"
julia = "1.9"

[extras]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[targets]
test = ["Test", "Statistics", "LinearAlgebra", "Zygote"]
